name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  buildServer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake
      - run: mkdir -p server/build && cd server/build && cmake .. && make
      - name: Run Unit tests
        run: server/build/test_app
      - name: Create deb package
        run: cd server && sh create_debpkg.sh
      - name: Run Smoke test
        run: cd server && sh smoke_test.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: server/http-server-dcsa.deb
  buildClient:
   runs-on: ubuntu-latest
   steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install docker
      - run: docker build -t client .
      - run: ls -l
      - run: cd /var/lib && ls -l
