name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake
      - run: mkdir -p server/build && cd server/build && cmake .. && make
      - run: server/build/test_app
      - run: cd server && sh create_debpkg.sh
      - run: sudo dpkg -i server/http-server-dcsa.deb
      - name: Make http-server-dcsa executable
      - run: chmod +x server/http-server-dcsa
      - name: Run http-server-dcsa
      - run: server/http-server-dcsa
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: server/http-server-dcsa.deb
