name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake
      - run: mkdir -p server/build && cd server/build && cmake .. && make
      - run: sh create_debpkg.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./http-server-dcsa.deb
